[package]
name = "turso"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = { workspace = true, features = ["derive"] }
rusql-alchemy = { workspace = true, features = ["turso"] }
sqlx.workspace = true
tokio = { workspace = true, features = ["full"] }
