[package]
name = "postgres"
version = "0.1.0"
edition = "2021"


[dependencies]
rusql-alchemy = { workspace = true, features = ["postgres"] }
sqlx.workspace = true
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true, features = ["derive"] }