[package]
name = "test-postgres"
version = "0.1.0"
edition = "2021"
workspace = ".."
publish = false


[dependencies]
anyhow.workspace = true
rusql-alchemy = { workspace = true, features = ["postgres"] }
sqlx.workspace = true
tokio = { workspace = true, features = ["full"] }
