[package]
name = "hello"
version = "0.1.2"
edition = "2021"
workspace = ".."
publish = false


[dependencies.rusql-alchemy]
path = "../.."

[dependencies]
sqlx = "^0.7.0"
rocket = { version = "^0.5.0", features = ["json"] }
serde = { version = "^1.0.203", features = ["derive"] }