[package]
name = "rocket-alchemy"
version = "0.1.0"
edition = "2021"
workspace = ".."


[dependencies]
rocket = { version = "^0.5.0", features = ["json"] }
serde = { version = "^1.0.203", features = ["derive"] }
rusql-alchemy  = { workspace = true , features = ["postgres"] }
sqlx.workspace = true
