[package]
name = "rocket"
version = "0.1.0"
edition = "2021"


[dependencies]
rocket = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
rusql-alchemy = { workspace = true, features = ["postgres"] }
sqlx.workspace = true
